apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PopcornPals-server
  template:
    metadata:
      labels:
        app: PopcornPals-server
    spec:
      containers:
        - name: popcorn-pals-server
          image: rangelplachkov/popcorn-pals-server:latest
          ports:
            - containerPort: 8080