
name: CD workflow

on:
  workflow_run:
      workflows: ["CI workflow"]
      types:
        - completed
      branches:
        - master

env:
  SERVER_PATH: PopcornPals-Server
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTION: 'temurin'
  OS_VERSION: ubuntu-latest   #${{ runner.os }}

jobs:        
  Clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Upload server code
        uses: actions/upload-artifact@v4
        with:
          name: server-code
          path: ${{ env.SERVER_PATH }}
  
  Build:
    runs-on: ubuntu-latest
    needs: Clone-repo
    steps:
      - name: Download server code
        uses: actions/download-artifact@v4
        with:
          name: server-code
          path: ${{ env.SERVER_PATH }}
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        working-directory: ${{ env.SERVER_PATH }}
        run: mvn clean install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.SERVER_PATH }}/target/*.jar

  Create-Dockerfile:
    runs-on: ubuntu-latest
    steps:
    
      - name: Create Dockerfile
        run: |
          echo "FROM eclipse-temurin:21-jre" > Dockerfile
          echo "COPY target/*.jar app.jar" >> Dockerfile
          echo "ENTRYPOINT [\"java\", \"-jar\", \"/app.jar\"]" >> Dockerfile
      
      - name: Upload Dockerfile
        uses: actions/upload-artifact@v4
        with:
          name: dockerfile
          path: Dockerfile
          
  Docker-Deploy:
    runs-on: ubuntu-latest
    needs: 
      - Create-Dockerfile
      - Build
    steps:

      - name: Download Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: dockerfile
          path: .

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check Docker Hub login status
        run: docker info

      - name: Build and push Docker image
        run: |
          docker build -t rangelplachkov/popcorn-pals-server:latest .
          docker push rangelplachkov/popcorn-pals-server:latest
