name: CI Pipeline

on:
  push:
    branches:
      - ci-cd-setup
  pull_request:
    branches:
      - ci-cd-setup

jobs:
  build:
    runs-on: windows-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    # Set up JDK for server (AdoptOpenJDK on Windows)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and test server
        run: |
          cd PopcornPals-Server
          mvn -e -X clean install
