name: OWASP Dependency-Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  owasp-dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --batch-mode --errors --file pom.xml

      - name: Download OWASP Dependency-Check
        run: |
          wget https://dl.bintray.com/jeremy-long/owasp/dependency-check-7.2.0-release.zip
          unzip dependency-check-7.2.0-release.zip

      - name: Run OWASP Dependency-Check
        run: |
          cd dependency-check/bin
          ./dependency-check.sh --project "MyJavaMavenProject" --scan $GITHUB_WORKSPACE/$APP_FOLDER

      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report.html
